name: nodes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  leak_tracker: ^10.0.0
  leak_tracker_flutter_testing: ^2.0.1
  leak_tracker_testing: ^2.0.1
  material_color_utilities: 0.8.0  # Match the version required by flutter_test
  meta: 1.11.0  # Match the version required by Flutter SDK
  test_api: 0.6.1  # Match the version required by flutter_test
  vm_service: 13.0.0  # Match the version required by flutter_test

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
